name: Build
on:
  workflow_run:
    workflows: ["SonarCloud", "Snyk Python Security Analysis", "Snyk IaC Security Analysis"]
    types:
      - completed
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Docker command
        run: |
          docker run -v ${PWD}:/var/task -w /var/task amazonlinux /bin/bash -c "yum install -y python3-pip && pip3 install --platform manylinux2014_x86_64 --target lambda_layer/python --python-version 3.12 --only-binary=:all: -r requirements.txt"

      - name: Copy src and layer
        run: cp -a src terraform/src && cp -a lambda_layer terraform/lambda_layer

      - name: Upload src and layer as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: code-artifacts
          path: |
            terraform/src
            terraform/lambda_layer